name: Centralized workflow
on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  ui:
    uses: folio-org/.github/.github/workflows/ui.yml@v1.5
    if: github.ref_name == github.event.repository.default_branch || github.event_name != 'push' || github.ref_type == 'tag'
    secrets: inherit
    with:
      jest-enabled: false
      sonar-sources: .
      compile-translations: false
      generate-module-descriptor: false
      publish-module-descriptor: false

